version: '3'
services:
  supportbot:
    build: .
    #image: "bostrot/telegram-support-bot:latest"
    restart: always
    volumes:
      - ${PWD}/config:/bot/config
    ports:
      - "6000:6000"
