# bot settings
bot_token: "1298895115:AAEtGH1iDcNI0JXBvMiNi3zxMlkBQmhETSc" # support bot tok                                                                                                             en
staffchat_id: "-1001556476694" # eg. -123456789
owner_id: "584512128"
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private

auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server
web_server_ssl_cert: '../src/web/ssl.crt' # Path for SSL cert
web_server_ssl_key: '../src/web/ssl.key' # Path for SSL key

dev_mode: true # Enable/disable dev mode

# customize your language
language:
    startCommandText: "Вітаємо в боті Відбіркової комісії ФІОТ! Залиште ваше питання і очікуйте відповідь."
    faqCommandText: "Не треба"
    helpCommandText: "<b>Доступні команди:</b>    /help    /faq    /id"
    contactMessage: "Дякуємо за запит! Очікуйте"
    blockedSpam: "You sent quite a number of questions in the last while. Please calm down and wait until staff reviews them."
    ticket: "Запит"
    closed: "закрито"
    acceptedBy: "прийнято"
    dear: "Дорогий(а)"
    regards: "Всього найкращого,"
    from: "від"
    language: "Українська"
    msg_sent: "Повідомлення відправлено користувачу"
    file_sent: "Файл відправлено користувачу"
    usr_with_ticket: "Користувач із запитом"
    banned: "заблоковано"
    replyPrivate: "Reply in private"
    services: "Select a service from the list below"
    customer: "customer"
    msgForwarding: "You messages will now be forwarded to vendors of the group: "
    back: "Go back"
    whatSubCategory: "Which subcategory describes your needs the best? "
    prvChatEnded: "Private chat ended."
    prvChatOpened: "Private Chat opened with customer."
    prvChatEnd: "End Private chat"
    prvChatOpenedCustomer: "Opened private chat"
    instructionsSent: "Instructions were sent to you in private chat."
    openTickets: "Open Tickets"
    support: "Support"
    prvChatOnly: "This command can be used in private chat only."
    ticketClosed: "Your ticket was closed by our staff. You can open a new ticket at any time."
    links: "Direct support links"
    textFirst: "Please send us a message before sending an image so that we can help you better."
    ticketClosedError: "You cannot reply to a closed ticket."
    automatedReply: "This is an automated reply."
    automatedReplyAuthor: "BottyBot."
    doesntHelp: "This does not help."
    automatedReplySent: "Automated reply was send to the user."
    ticketReopened: "Ticket reopened."

# categories: 
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups: 
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910" 
#  - name: "Contact"
#    msg: "Check out our Website"

    
  
